version: '3.3'

volumes:
  pg_data:
  static_scm:
  media_scm:


services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  scm:
    image: agas0077/scm:latest
    env_file: .env
    depends_on:
      - db
    restart: on-failure:2
    volumes:
      - static_scm:/app/staticfiles/
      - media_scm:/app/media/
    command: >
      bash -c "python manage.py migrate 
      && python manage.py collectstatic --no-input
      && gunicorn --bind 0.0.0.0:8000 scm.wsgi"

  nginx:
    depends_on:
        - scm
    image: nginx:1.19.3
    ports:
      - "8002:80"
    volumes:
      - ./nginx/scm.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_scm:/static
      - media_scm:/media