# Generated by Django 4.2.1 on 2023-05-26 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMentorMenteeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('basementormenteemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mentor.basementormenteemodel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            bases=('mentor.basementormenteemodel',),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('basementormenteemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mentor.basementormenteemodel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            bases=('mentor.basementormenteemodel',),
        ),
        migrations.CreateModel(
            name='MentorMentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_mentee_mentee', to='mentor.mentee', verbose_name='Менти')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_mentee_mentor', to='mentor.mentor', verbose_name='Ментор')),
            ],
        ),
    ]
