# Generated by Django 4.2.1 on 2023-05-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_alter_mentormentee_mentee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentormentee',
            name='mentor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_mentee_mentor', to='mentor.mentor', verbose_name='Ментор'),
        ),
    ]
