# Generated by Django 4.2.1 on 2023-05-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_basementormenteemodel_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentormentee',
            name='status',
            field=models.CharField(choices=[('not start', 'Еще не начали работу'), ('at work', 'Начали работу'), ('end work', 'Закончили работу')], default='not start', max_length=50, verbose_name='Статус пары'),
        ),
    ]
