# Generated by Django 4.2.1 on 2023-06-08 10:08

# Third Party Library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0006_mentormentee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basementormenteemodel',
            name='description',
            field=models.TextField(verbose_name='Мотивация и ожидания'),
        ),
    ]
