# Generated by Django 4.2.1 on 2023-05-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Изображение')),
                ('speaker', models.CharField(max_length=100, verbose_name='Спикер')),
                ('format', models.CharField(choices=[('Online', 'Онлайн'), ('offline', 'Оффлайн'), ('hybrid', 'Гибрид')], default='offline', max_length=7, verbose_name='Формат')),
                ('text', models.TextField(verbose_name='Краткое описание')),
            ],
        ),
    ]
