# Generated by Django 4.2.1 on 2023-05-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_news_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('ONLINE', 'Онлайн'), ('OFFLINE', 'Оффлайн'), ('HYBRID', 'Гибрид')], default='OFFLINE', max_length=7, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
