# Generated by Django 4.2.1 on 2023-05-26 15:00

# Third Party Library
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_alter_eventmember_event_alter_eventmember_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_member_event', to='events.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_member_member', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
    ]
