# Generated by Django 4.2.1 on 2023-05-22 14:09

# Third Party Library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='member',
            name='staff_job',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность в проекте'),
        ),
    ]
