# Generated by Django 4.2.1 on 2023-05-22 14:34

# Third Party Library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_education_member_image_member_staff_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='telegram',
            field=models.CharField(error_messages='Формат должен быть: @ник', max_length=200, unique=True, verbose_name='Ник в Telegram'),
        ),
    ]
