# Generated by Django 4.2.1 on 2023-05-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный пользователь'),
        ),
    ]
