# Generated by Django 4.2.1 on 2023-05-31 09:19

# Third Party Library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='terms_agree',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
