# Generated by Django 4.2.1 on 2023-06-08 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_terms_agree'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/', verbose_name='Лого компании')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с такой почтой уже зарегистрирован'}, max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_num',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким номером уже зарегистрирован'}, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Формат должен быть: +99999999999', regex='^\\+?\\d{8,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='member',
            name='telegram',
            field=models.CharField(max_length=200, unique=True, verbose_name='Ник в Telegram'),
        ),
    ]
