# Generated by Django 4.2.1 on 2023-06-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_companylogo_alter_member_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyLogo',
        ),
    ]
